apiVersion: extensions/v1beta1
kind: "Deployment"
metadata:
  name: #{DOCKER_IMAGE}-#{VERSION}
  namespace: #{APP_NAME}
  labels:
    app: #{DOCKER_IMAGE}
    release: #{DOCKER_IMAGE}-v#{VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{DOCKER_IMAGE}
      release: #{DOCKER_IMAGE}-v#{VERSION}
  template:
    metadata:
      labels:
        app: #{DOCKER_IMAGE}
        release: #{DOCKER_IMAGE}-v#{VERSION}
    spec:
      containers:
      - name: #{DOCKER_IMAGE}
        image: #{DOCKER_HOST}/#{DOCKER_IMAGE}:#{VERSION}
        env:
        - name: API_SERVER
          value: "http://localhost:9000"
        ports:
        - containerPort: 4200
          protocol: TCP
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "300Mi"
            cpu: "500m"  