apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: #{DOCKER_IMAGE}-hpa
  namespace: #{APP_NAME}
  labels:
    app: #{DOCKER_IMAGE}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: #{DOCKER_IMAGE}-#{VERSION}
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80