apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: #{APP_NAME}-hpa
  namespace: #{APP_NAME}
  labels:
    app: #{APP_NAME}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: #{APP_NAME}-#{VERSION}
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80